// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwlisdakbpqtrxjbqvbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3bGlzZGFrYnBxdHJ4amJxdmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzQzMDIsImV4cCI6MjA2MjgxMDMwMn0.g_R4gN1k6rsZ4WEwbyHIbtOzw6sdiUBKIdQUtPvvr8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);